# Generated by Django 5.2.1 on 2025-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typepayout',
            options={'verbose_name': 'Платёж', 'verbose_name_plural': 'Тип платежей'},
        ),
        migrations.AlterField(
            model_name='recordcash',
            name='create',
            field=models.DateTimeField(verbose_name='Время добавления'),
        ),
    ]
